### ISSUE TITLE
Add example to documentation :-)

### ISSUE THREAD

**Issue by jkrenge** [dashed/detour-stream#2]
Hi there! Sorry, unfortunately I didn't understand how to use the module. 

I tried:

```
var detour = require('detour-stream');

stream = fs
  .createReadStream(filepath)
  .detour(someBoolean, decodeStream(someOptions))
  .pipe(writeStream);
```

But this results in:

```
  .detour(someBoolean, decodeStream(someOptions))
 ^
TypeError: undefined is not a function
```

If you don't mind, I asked a [question on SO](http://stackoverflow.com/questions/35605827/conditionally-pipe-streams-in-node-js).

**Comment by dashed** [comment]
@jkrenge `detour` is a function that creates a writable stream: https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options

Thus, from your example, this should work:

```js
var detour = require('detour-stream');

stream = fs
  .createReadStream(filepath)
  .pipe(detour(someBoolean, decodeStream(someOptions))) // just pipe it
  .pipe(writeStream);
```

**Comment by dashed** [comment]
Closing since this seems resolved 😄 : http://stackoverflow.com/questions/35605827/conditionally-pipe-streams-in-node-js#comment64022822_38272514
